ci: debug secret

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -103,6 +103,14 @@ jobs:
             type=semver,priority=400,pattern={{major}},value=${{ steps.version.outputs.sem_version }}
       - uses: docker/setup-qemu-action@v3
       - uses: docker/setup-buildx-action@v3
+      - name: check secret presence
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "Secret is missing"
+            exit 1
+          else
+            echo "Secret is present"
+          fi
       - uses: docker/login-action@v3
         with:
           username: forgeforgitea
